### PR TITLE
Add IGNORE_URLS setting

### PR DESCRIPTION
**Pull request by Iftahh**
This (optional) setting will allow a user to opt-out of the
middleware for certain URLs.

The setting is a list of strings, which are the paths of
urls to ignore. The paths can be written with prefix '/'
and/or suffix '/', or without them.

Related to issue #37

### CODE REVIEW

**Comment by Iftahh** [comment]
I had to split the config.__init__ because pyflakes complained that the function became too complex.

I didn't modify the tests, but tested manually the /no_guid url in the demoproject

**Comment by JonasKs** [comment]
Thank you! I’ll look a bit more careful over when I get on a computer, but off the bat it looks good! 

I would love both some docs (in the `README.rst` and `docs/settings.rst`) and a few more tests(unit test for the config and one real test where logs are checked.) I don’t mind doing these things for you if you don’t want to or don’t have experience with pytest. Let me know :)

**Comment by Iftahh** [comment]
Yes, please do :)
I never worked with pytest before (but read about it and it looks great) - so it will probably take you less time than me.

Thanks

**Comment by JonasKs** [comment]
Alright! Busy times but I'll do it this week.

**Comment by JonasKs** [comment]
Could you please allow changes from contributors? See [GitHub Docs](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

**Comment by JonasKs** [comment]
Also please update `CONTRIBUTORS.rst`.

Something like this:

```rst
* Iftahh | `@Iftahh <https://github.com/Iftahh>`_
```

**Comment by Iftahh** [comment]
Sorry, busy times here as well -
"Allow edits from maintainers." is already checked, you should be able to make changes.

I'll have some time over the weekend to make the changes myself if you prefer

**Comment by JonasKs** [comment]
Strange, I tried but it didn’t work. I’ll check it out again tomorrow. 

I’ve got everything ready locally. :)

**Comment by JonasKs** [comment]
Seems to be an issue with Github workflows atm. I'll rerun them later.

**Comment by JonasKs** [comment]
Please also feel free to add yourself to the `CONTRIBUTORS.rst` file before I merge :) 

Example:   
```rst
* Iftahh | `@Iftahh <https://github.com/Iftahh>`_
```

**Comment by JonasKs** [comment]
Merged. PyPi pipeline is running. :) Thank you!

**Pull request merged**
